// <auto-generated />
using ConsoleApp39.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp39.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260921224009_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp39.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("No category name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Books"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Home"
                        });
                });

            modelBuilder.Entity("ConsoleApp39.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("No product name");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Price = 1800m,
                            ProductName = "Laptop",
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Price = 30m,
                            ProductName = "Mouse",
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Price = 70m,
                            ProductName = "Keyboard",
                            Stock = 35
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Price = 25m,
                            ProductName = "T-Shirt",
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Price = 60m,
                            ProductName = "Jeans",
                            Stock = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Price = 120m,
                            ProductName = "Jacket",
                            Stock = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Price = 35m,
                            ProductName = "C# Book",
                            Stock = 40
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Price = 40m,
                            ProductName = "SQL Book",
                            Stock = 30
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Price = 45m,
                            ProductName = "C++ Book",
                            Stock = 20
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Price = 30m,
                            ProductName = "Football",
                            Stock = 60
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Price = 35m,
                            ProductName = "Basketball",
                            Stock = 45
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Price = 100m,
                            ProductName = "Tennis Racket",
                            Stock = 15
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Price = 250m,
                            ProductName = "Table",
                            Stock = 10
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Price = 80m,
                            ProductName = "Chair",
                            Stock = 30
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Price = 50m,
                            ProductName = "Lamp",
                            Stock = 40
                        });
                });

            modelBuilder.Entity("ConsoleApp39.Models.Product", b =>
                {
                    b.HasOne("ConsoleApp39.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ConsoleApp39.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
